POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
	"firstname": "Odo",
	"lastname": "Peter",
	"username": "Odopeter",
	"password": "123456",
	"options": [{
		"homeOptions": {
			"icon": "<FaHome />",
			"id": "1",
			"name": "Education",
			"value": "trending education channels videos"
		},

		"musicOptionsOne": {
			"icon": "<HiMusicNote />",
			"id": "2",
			"name": "Hip Hop",
			"value": "trending hip hop music videos"
		},
		"musicOptionsTwo": {
			"icon": "<HiMusicNote />",
			"id": "2",
			"name": "Drill",
			"value": "trending drill music videos"
		},

		"gamingOptionsOne": {
			"icon": "<GiGamepad />",
			"id": "3",
			"name": "God of War",
			"value": "god of war gameplay"
		},

		"gamingOptionsTwo": {
			"icon": "<GiGamepad />",
			"id": "3",
			"name": "Car Race",
			"value": "car race games gameplay"
		},

		"animeOptionsOne": {
			"icon": "<MdOndemandVideo />",
			"id": "4",
			"name": "One Piece",
			"value": "one piece anime"
		},

		"animeOptionsTwo": {
			"icon": "<MdOndemandVideo />",
			"id": "4",
			"name": "AOT",
			"value": "attack on titans anime"
		},

		"codingOptionsOne": {
			"icon": "<MdCode />",
			"id": "5",
			"name": "Game Dev",
			"value": "game development coding videos"
		},

		"codingOptionsTwo": {
			"icon": "<MdCode />",
			"id": "5",
			"name": "Web Dev",
			"value": "web development coding videos"
		},

		"educationOptionsOne": {
			"icon": "<FaUserGraduate />",
			"id": "6",
			"name": "Trending'",
			"value": "trending education channels videos"
		},

		"educationOptionsTwo": {
			"icon": "<FaUserGraduate />",
			"id": "6",
			"name": "Khan Academy",
			"value": "popular khan academy videos"
		},

		"moviesOptionsOne": {
			"icon": "<MdPersonalVideo />",
			"id": "7",
			"name": "Crime",
			"value": "popular crime movies trailers"
		},

		"moviesOptionsTwo": {
			"icon": "<MdPersonalVideo />",
			"id": "7",
			"name": "Trending",
			"value": "trending box office movies trailers"
		}
	}]
}

###
POST http://localhost:3001/api/login HTTP/1.1
content-type: application/json

{
    "username" : "Odopeter",
    "password": "123456"
}

